#!/usr/bin/env bash
set -euo pipefail

# VPS TCP Optimize + Argo VMess WebSocket OneClick
# V1 strategy:
# - TCP optimize: call the isolated menu-66 entry preserved from vps-tcp-tune.
# - Argo VMess+WS: call the archived ArgoX script in non-interactive config mode,
#   forcing INSTALL_PROTOCOLS=(f), i.e. VMess + WS only.

REPO_RAW_BASE="https://raw.githubusercontent.com/cshaizhihao/vps-tcp-argo-toolkit/main"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd 2>/dev/null || echo .)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd 2>/dev/null || echo .)"

TCP_SCRIPT_LOCAL="${SCRIPT_DIR}/tcp-one-click-optimize.sh"
ARGOX_SCRIPT_LOCAL="${SCRIPT_DIR}/upstream/argox.sh"

WORK_DIR="/etc/vps-argo-vmess"
CONFIG_FILE="${WORK_DIR}/install.conf"
LOG_FILE="${WORK_DIR}/install.log"

DEFAULT_START_PORT="30000"
DEFAULT_NGINX_PORT="8001"
DEFAULT_WS_PATH="argox"
DEFAULT_NODE_NAME="VPS-Argo-VMess"

info() { printf '\033[36m[INFO]\033[0m %s\n' "$*"; }
success() { printf '\033[32m[DONE]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[WARN]\033[0m %s\n' "$*"; }
err() { printf '\033[31m[ERR ]\033[0m %s\n' "$*" >&2; }

require_root() {
  if [ "$(id -u)" != "0" ]; then
    err "请使用 root 执行：sudo -i 后重新运行"
    exit 1
  fi
}

fetch_or_run_script() {
  local local_path="$1"
  local raw_path="$2"
  shift 2
  if [ -s "$local_path" ]; then
    bash "$local_path" "$@"
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/${raw_path}") "$@"
  fi
}

run_tcp_optimize() {
  require_root
  info "启动 TCP 一键全自动优化：XanMod + BBR v3 + 网络调优"
  fetch_or_run_script "$TCP_SCRIPT_LOCAL" "scripts/tcp-one-click-optimize.sh"
}

gen_uuid() {
  if [ -r /proc/sys/kernel/random/uuid ]; then
    cat /proc/sys/kernel/random/uuid
  elif command -v uuidgen >/dev/null 2>&1; then
    uuidgen | tr 'A-Z' 'a-z'
  else
    cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1 | sed -E 's/(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/'
  fi
}

write_argox_vmess_config() {
  require_root
  mkdir -p "$WORK_DIR"

  local uuid="${UUID:-}"
  local ws_path="${WS_PATH:-$DEFAULT_WS_PATH}"
  local start_port="${START_PORT:-$DEFAULT_START_PORT}"
  local nginx_port="${NGINX_PORT:-$DEFAULT_NGINX_PORT}"
  local node_name="${NODE_NAME:-$DEFAULT_NODE_NAME}"
  local argo_domain="${ARGO_DOMAIN:-}"
  local argo_auth="${ARGO_AUTH:-}"
  local server="${SERVER:-}"
  local server_port="${SERVER_PORT:-443}"

  [ -n "$uuid" ] || uuid="$(gen_uuid)"

  cat > "$CONFIG_FILE" <<EOF
# Generated by vps-argo-vmess-oneclick.sh
# Force ArgoX to install VMess + WS only.
INSTALL_PROTOCOLS=(f)
START_PORT=${start_port}
VMESS_WS_PORT=${start_port}
NGINX_PORT=${nginx_port}
UUID='${uuid}'
WS_PATH='${ws_path}'
NODE_NAME='${node_name}'
EOF

  # Optional fixed Argo tunnel / preferred CDN settings.
  [ -n "$argo_domain" ] && printf "ARGO_DOMAIN='%s'\n" "$argo_domain" >> "$CONFIG_FILE"
  [ -n "$argo_auth" ] && printf "ARGO_AUTH='%s'\n" "$argo_auth" >> "$CONFIG_FILE"
  [ -n "$server" ] && printf "SERVER='%s'\nSERVER_PORT='%s'\n" "$server" "$server_port" >> "$CONFIG_FILE"

  chmod 600 "$CONFIG_FILE"
  success "已生成 Argo VMess+WS 配置：$CONFIG_FILE"
  info "协议固定：VMess + WebSocket；WS Path：/${ws_path}-vm；内部端口：${start_port}；Nginx 端口：${nginx_port}"
}

install_argo_vmess_ws() {
  require_root
  write_argox_vmess_config
  info "启动 ArgoX 非交互安装，仅启用 VMess + WS"
  mkdir -p "$WORK_DIR"
  # -f: source config file; -l: Chinese output. ArgoX will install cloudflared/xray/nginx and export node URLs.
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -f "$CONFIG_FILE" -l 2>&1 | tee "$LOG_FILE"
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -f "$CONFIG_FILE" -l 2>&1 | tee "$LOG_FILE"
  fi
  success "Argo VMess+WS 安装流程结束"
  show_argo_vmess_ws_info || true
}

show_argo_vmess_ws_info() {
  require_root
  if [ -s /etc/argox/list ]; then
    cat /etc/argox/list
    return 0
  fi
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -n
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -n
  fi
}

uninstall_argo_vmess_ws() {
  require_root
  warn "将调用 ArgoX 原卸载流程，卸载 Argo/Xray/Nginx 相关配置"
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -u
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -u
  fi
}

run_all() {
  run_tcp_optimize
  warn "如果刚安装 XanMod 内核并选择重启，重启后需再次执行 --install-argo-vmess 或 --all 继续 Argo 部分。"
  install_argo_vmess_ws
}

usage() {
  cat <<'EOF'
VPS TCP Optimize + Argo VMess+WS OneClick

Usage:
  bash vps-argo-vmess-oneclick.sh [command]

Commands:
  --optimize             执行全自动 TCP 优化：BBR v3 + 网络调优
  --install-argo-vmess   安装/重装 Argo VMess + WS，并生成节点/订阅 URL
  --all                  先执行 TCP 优化，再安装 Argo VMess + WS
  --show-url             查看已生成的节点/订阅信息
  --uninstall-argo       卸载 Argo VMess + WS 相关服务
  --write-config         仅生成 Argo VMess + WS 配置文件，不安装
  -h, --help             显示帮助

Optional environment variables:
  UUID                   指定 VMess UUID，默认自动生成
  WS_PATH                指定 WS Path 前缀，默认 argox，实际 path 为 /<WS_PATH>-vm
  START_PORT             指定 Xray VMess 内部监听端口，默认 30000
  NGINX_PORT             指定 Nginx/Argo 本地入口端口，默认 8001
  NODE_NAME              指定节点名，默认 VPS-Argo-VMess
  ARGO_DOMAIN            固定 Argo 域名；不填则使用 trycloudflare 临时域名
  ARGO_AUTH              Argo Token / Json / Cloudflare API 信息；固定隧道时使用
  SERVER                 优选 CDN 地址，默认使用 ArgoX 内置优选
  SERVER_PORT            优选 CDN 端口，默认 443

Examples:
  bash vps-argo-vmess-oneclick.sh --all
  WS_PATH=zaki NODE_NAME=Zaki-VPS bash vps-argo-vmess-oneclick.sh --install-argo-vmess
  ARGO_DOMAIN=tunnel.example.com ARGO_AUTH='eyJhIj...' bash vps-argo-vmess-oneclick.sh --install-argo-vmess
EOF
}

menu() {
  cat <<'EOF'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 VPS TCP Optimize + Argo VMess+WS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. 执行全自动 TCP 优化（BBR v3 + 网络调优）
2. 安装/重装 Argo VMess + WS
3. 一键执行：TCP 优化 + Argo VMess + WS
4. 查看节点/订阅信息
5. 卸载 Argo VMess + WS
0. 退出
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
  read -r -p "请输入选择: " choice
  case "$choice" in
    1) run_tcp_optimize ;;
    2) install_argo_vmess_ws ;;
    3) run_all ;;
    4) show_argo_vmess_ws_info ;;
    5) uninstall_argo_vmess_ws ;;
    0) exit 0 ;;
    *) err "无效选择"; exit 1 ;;
  esac
}

case "${1:-}" in
  --optimize) run_tcp_optimize ;;
  --install-argo-vmess) install_argo_vmess_ws ;;
  --all) run_all ;;
  --show-url) show_argo_vmess_ws_info ;;
  --uninstall-argo) uninstall_argo_vmess_ws ;;
  --write-config) write_argox_vmess_config ;;
  -h|--help) usage ;;
  "") menu ;;
  *) err "未知参数：$1"; usage; exit 1 ;;
esac
