#!/usr/bin/env bash
set -euo pipefail

# VPS TCP Optimize + Argo VMess WebSocket OneClick
# V1 strategy:
# - TCP optimize: call the isolated menu-66 entry preserved from vps-tcp-tune.
# - Argo VMess+WS: call the archived ArgoX script in non-interactive config mode,
#   forcing INSTALL_PROTOCOLS=(f), i.e. VMess + WS only.

REPO_RAW_BASE="https://raw.githubusercontent.com/cshaizhihao/vps-tcp-argo-toolkit/main"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd 2>/dev/null || echo .)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd 2>/dev/null || echo .)"

TCP_SCRIPT_LOCAL="${SCRIPT_DIR}/tcp-one-click-optimize.sh"
ARGOX_SCRIPT_LOCAL="${SCRIPT_DIR}/upstream/argox.sh"

WORK_DIR="/etc/vps-argo-vmess"
CONFIG_FILE="${WORK_DIR}/install.conf"
LOG_FILE="${WORK_DIR}/install.log"
STATE_FILE="${WORK_DIR}/state.env"
INSTALLED_BIN="/usr/local/bin/speed"

DEFAULT_START_PORT="30000"
DEFAULT_NGINX_PORT="8001"
DEFAULT_WS_PATH="argox"
DEFAULT_NODE_NAME="VPS-Argo-VMess"

info() { printf '\033[36m[INFO]\033[0m %s\n' "$*"; }
success() { printf '\033[32m[DONE]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[WARN]\033[0m %s\n' "$*"; }
err() { printf '\033[31m[ERR ]\033[0m %s\n' "$*" >&2; }

require_root() {
  if [ "$(id -u)" != "0" ]; then
    err "请使用 root 执行：sudo -i 后重新运行"
    exit 1
  fi
}

fetch_or_run_script() {
  local local_path="$1"
  local raw_path="$2"
  shift 2
  if [ -s "$local_path" ]; then
    bash "$local_path" "$@"
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/${raw_path}") "$@"
  fi
}

install_shortcut() {
  require_root
  mkdir -p "$WORK_DIR"
  if [ -s "${BASH_SOURCE[0]}" ]; then
    cp "${BASH_SOURCE[0]}" "$INSTALLED_BIN"
  else
    curl -fsSL "${REPO_RAW_BASE}/scripts/vps-argo-vmess-oneclick.sh" -o "$INSTALLED_BIN"
  fi
  chmod +x "$INSTALLED_BIN"
  success "已安装快捷命令：speed"
  echo "以后可直接执行："
  echo "  speed"
  echo "  speed --continue"
  echo "  speed --all"
}

save_pending_state() {
  require_root
  mkdir -p "$WORK_DIR"
  cat > "$STATE_FILE" <<EOF
PENDING_CONTINUE=1
CREATED_AT=$(date -Is 2>/dev/null || date)
NEXT_ACTION=continue
EOF
  chmod 600 "$STATE_FILE"
}

clear_state() {
  require_root
  rm -f "$STATE_FILE"
  success "已清理续跑状态：$STATE_FILE"
}

is_xanmod_kernel() {
  uname -r | grep -qi xanmod
}

show_continue_hint() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " 下一步"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "如果本次安装了 XanMod/BBR v3 内核，请重启服务器。"
  echo "重启后执行："
  echo ""
  echo "  speed --continue"
  echo ""
  echo "它会继续完成：TCP 网络调优 + Argo VMess+WS 安装 + 健康检查。"
}

run_tcp_optimize() {
  require_root
  install_shortcut || true
  if ! is_xanmod_kernel; then
    save_pending_state
  fi
  info "启动 TCP 一键全自动优化：XanMod + BBR v3 + 网络调优"
  fetch_or_run_script "$TCP_SCRIPT_LOCAL" "scripts/tcp-one-click-optimize.sh"
  if ! is_xanmod_kernel; then
    show_continue_hint
  fi
}

gen_uuid() {
  if [ -r /proc/sys/kernel/random/uuid ]; then
    cat /proc/sys/kernel/random/uuid
  elif command -v uuidgen >/dev/null 2>&1; then
    uuidgen | tr 'A-Z' 'a-z'
  else
    cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1 | sed -E 's/(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/'
  fi
}

write_argox_vmess_config() {
  require_root
  mkdir -p "$WORK_DIR"

  local uuid="${UUID:-}"
  local ws_path="${WS_PATH:-$DEFAULT_WS_PATH}"
  local start_port="${START_PORT:-$DEFAULT_START_PORT}"
  local nginx_port="${NGINX_PORT:-$DEFAULT_NGINX_PORT}"
  local node_name="${NODE_NAME:-$DEFAULT_NODE_NAME}"
  local argo_domain="${ARGO_DOMAIN:-}"
  local argo_auth="${ARGO_AUTH:-}"
  local server="${SERVER:-}"
  local server_port="${SERVER_PORT:-443}"

  [ -n "$uuid" ] || uuid="$(gen_uuid)"

  cat > "$CONFIG_FILE" <<EOF
# Generated by vps-argo-vmess-oneclick.sh
# Force ArgoX to install VMess + WS only.
INSTALL_PROTOCOLS=(f)
START_PORT=${start_port}
VMESS_WS_PORT=${start_port}
NGINX_PORT=${nginx_port}
UUID='${uuid}'
WS_PATH='${ws_path}'
NODE_NAME='${node_name}'
EOF

  # Optional fixed Argo tunnel / preferred CDN settings.
  [ -n "$argo_domain" ] && printf "ARGO_DOMAIN='%s'\n" "$argo_domain" >> "$CONFIG_FILE"
  [ -n "$argo_auth" ] && printf "ARGO_AUTH='%s'\n" "$argo_auth" >> "$CONFIG_FILE"
  [ -n "$server" ] && printf "SERVER='%s'\nSERVER_PORT='%s'\n" "$server" "$server_port" >> "$CONFIG_FILE"

  chmod 600 "$CONFIG_FILE"
  success "已生成 Argo VMess+WS 配置：$CONFIG_FILE"
  info "协议固定：VMess + WebSocket；WS Path：/${ws_path}-vm；内部端口：${start_port}；Nginx 端口：${nginx_port}"
}

install_argo_vmess_ws() {
  require_root
  write_argox_vmess_config
  info "启动 ArgoX 非交互安装，仅启用 VMess + WS"
  mkdir -p "$WORK_DIR"
  # -f: source config file; -l: Chinese output. ArgoX will install cloudflared/xray/nginx and export node URLs.
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -f "$CONFIG_FILE" -l 2>&1 | tee "$LOG_FILE"
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -f "$CONFIG_FILE" -l 2>&1 | tee "$LOG_FILE"
  fi
  success "Argo VMess+WS 安装流程结束"
  show_argo_vmess_ws_info || true
  summarize_result || true
  health_check || true
}

show_argo_vmess_ws_info() {
  require_root
  if [ -s /etc/argox/list ]; then
    cat /etc/argox/list
    return 0
  fi
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -n
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -n
  fi
}

uninstall_argo_vmess_ws() {
  require_root
  warn "将调用 ArgoX 原卸载流程，卸载 Argo/Xray/Nginx 相关配置"
  if [ -s "$ARGOX_SCRIPT_LOCAL" ]; then
    bash "$ARGOX_SCRIPT_LOCAL" -u
  else
    bash <(curl -fsSL "${REPO_RAW_BASE}/scripts/upstream/argox.sh") -u
  fi
}

run_all() {
  install_shortcut || true
  if ! is_xanmod_kernel; then
    save_pending_state
    run_tcp_optimize
    show_continue_hint
    return 0
  fi
  run_tcp_optimize
  install_argo_vmess_ws
  clear_state || true
}

continue_after_reboot() {
  require_root
  install_shortcut || true
  if ! is_xanmod_kernel; then
    err "当前仍未进入 XanMod 内核，暂停继续安装 Argo，避免循环。"
    echo "当前内核: $(uname -r)"
    echo "建议检查 VPS 是否支持自定义内核、GRUB 启动项或重新执行 speed --optimize。"
    exit 1
  fi
  info "检测到 XanMod 内核，继续执行 TCP 网络调优 + Argo VMess+WS"
  run_tcp_optimize
  install_argo_vmess_ws
  clear_state || true
}

check_environment() {
  require_root
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Speed Argo TCP · 环境检测"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "系统内核: $(uname -r)"
  echo "系统架构: $(uname -m)"
  echo "Root 权限: OK"
  for cmd in curl wget bash systemctl ss openssl; do
    if command -v "$cmd" >/dev/null 2>&1; then
      printf "%-12s: OK\n" "$cmd"
    else
      printf "%-12s: MISSING\n" "$cmd"
    fi
  done
  echo "TCP 拥塞控制: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  echo "默认队列算法: $(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  if [ -s /etc/argox/list ]; then
    echo "ArgoX 节点信息: FOUND /etc/argox/list"
  else
    echo "ArgoX 节点信息: NOT FOUND"
  fi
}

summarize_result() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Speed Argo TCP · 结果摘要"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "内核: $(uname -r)"
  echo "拥塞控制: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo unknown)"
  echo "队列算法: $(sysctl -n net.core.default_qdisc 2>/dev/null || echo unknown)"
  if [ -s /etc/argox/list ]; then
    echo ""
    echo "Argo VMess+WS 节点/订阅信息已生成："
    grep -E 'vmess://|https?://.*/(base64|auto|clash|shadowrocket)|trycloudflare\.com|Index:|V2rayN|Nekoray' /etc/argox/list || true
    echo ""
    echo "完整信息：/etc/argox/list"
  else
    echo ""
    echo "未检测到 /etc/argox/list；如果刚完成 TCP 内核安装并重启，请重启后执行 --install-argo-vmess。"
  fi
}

service_state() {
  local svc="$1"
  if command -v systemctl >/dev/null 2>&1; then
    if systemctl is-active --quiet "$svc" 2>/dev/null; then
      echo "running"
    elif systemctl list-unit-files "$svc" >/dev/null 2>&1 || systemctl status "$svc" >/dev/null 2>&1; then
      echo "installed-but-not-running"
    else
      echo "not-found"
    fi
  else
    if pgrep -f "$svc" >/dev/null 2>&1; then
      echo "running"
    else
      echo "unknown"
    fi
  fi
}

port_state() {
  local port="$1"
  if command -v ss >/dev/null 2>&1 && ss -lnt 2>/dev/null | awk '{print $4}' | grep -Eq "(:|\\])${port}$"; then
    echo "listening"
  else
    echo "not-listening"
  fi
}

health_check() {
  require_root
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Speed Argo TCP · 健康检查"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  local fail=0
  local argo_state xray_state nginx_state nginx_port argo_domain
  argo_state="$(service_state argo)"
  xray_state="$(service_state xray)"
  nginx_state="$(service_state nginx)"
  nginx_port="$(awk -F= '/^NGINX_PORT=/{print $2}' "$CONFIG_FILE" 2>/dev/null | tr -d "'\"")"
  nginx_port="${nginx_port:-8001}"

  printf "%-18s %s\n" "argo.service:" "$argo_state"
  printf "%-18s %s\n" "xray.service:" "$xray_state"
  printf "%-18s %s\n" "nginx.service:" "$nginx_state"
  printf "%-18s %s (%s)\n" "本地入口端口:" "$nginx_port" "$(port_state "$nginx_port")"

  [ "$argo_state" = "running" ] || fail=1
  [ "$xray_state" = "running" ] || fail=1
  [ "$(port_state "$nginx_port")" = "listening" ] || fail=1

  if [ -s /etc/argox/list ]; then
    echo "节点列表: FOUND /etc/argox/list"
    argo_domain="$(grep -Eo 'https?://[^/ ]+' /etc/argox/list | sed 's#https\?://##' | grep -E 'trycloudflare\.com|cloudflare|\.' | head -n1 || true)"
    [ -n "$argo_domain" ] && echo "Argo 域名: $argo_domain" || echo "Argo 域名: 未能从节点列表提取"
  else
    echo "节点列表: MISSING /etc/argox/list"
    fail=1
  fi

  if [ -s /etc/argox/subscribe/base64 ]; then
    echo "Base64订阅: FOUND"
  else
    echo "Base64订阅: MISSING"
    fail=1
  fi

  echo ""
  if [ "$fail" -eq 0 ]; then
    success "健康检查通过：Argo / Xray / 本地入口 / 订阅文件均可用"
    return 0
  fi

  warn "健康检查未完全通过，建议按以下方向排查："
  [ "$argo_state" = "running" ] || echo "- Argo 未运行：执行 systemctl status argo 或重新运行 --install-argo-vmess"
  [ "$xray_state" = "running" ] || echo "- Xray 未运行：执行 systemctl status xray，检查 /etc/argox/xray.log"
  [ "$(port_state "$nginx_port")" = "listening" ] || echo "- 本地入口端口未监听：检查 nginx 配置或端口占用 ss -lntp | grep $nginx_port"
  [ -s /etc/argox/list ] || echo "- 节点列表未生成：查看 $LOG_FILE，确认 Argo 是否拿到隧道域名"
  [ -s /etc/argox/subscribe/base64 ] || echo "- 订阅文件缺失：重新执行 --show-url 或 --install-argo-vmess"
  return 1
}

usage() {
  cat <<'EOF'
VPS TCP Optimize + Argo VMess+WS OneClick

Usage:
  bash vps-argo-vmess-oneclick.sh [command]

Commands:
  --optimize             执行全自动 TCP 优化：BBR v3 + 网络调优
  --install-argo-vmess   安装/重装 Argo VMess + WS，并生成节点/订阅 URL
  --all                  智能全流程；如需重启，重启后用 speed --continue 继续
  --continue             重启后继续：TCP 网络调优 + Argo VMess + WS
  --show-url             查看已生成的节点/订阅信息
  --uninstall-argo       卸载 Argo VMess + WS 相关服务
  --write-config         仅生成 Argo VMess + WS 配置文件，不安装
  --install-shortcut     安装 speed 快捷命令到 /usr/local/bin/speed
  --clear-state          清理续跑状态
  --check                检测当前环境和已安装状态
  --summary              输出结果摘要
  --health               安装后健康检查
  -h, --help             显示帮助

Optional environment variables:
  UUID                   指定 VMess UUID，默认自动生成
  WS_PATH                指定 WS Path 前缀，默认 argox，实际 path 为 /<WS_PATH>-vm
  START_PORT             指定 Xray VMess 内部监听端口，默认 30000
  NGINX_PORT             指定 Nginx/Argo 本地入口端口，默认 8001
  NODE_NAME              指定节点名，默认 VPS-Argo-VMess
  ARGO_DOMAIN            固定 Argo 域名；不填则使用 trycloudflare 临时域名
  ARGO_AUTH              Argo Token / Json / Cloudflare API 信息；固定隧道时使用
  SERVER                 优选 CDN 地址，默认使用 ArgoX 内置优选
  SERVER_PORT            优选 CDN 端口，默认 443

Examples:
  bash vps-argo-vmess-oneclick.sh --all
  WS_PATH=zaki NODE_NAME=Zaki-VPS bash vps-argo-vmess-oneclick.sh --install-argo-vmess
  ARGO_DOMAIN=tunnel.example.com ARGO_AUTH='eyJhIj...' bash vps-argo-vmess-oneclick.sh --install-argo-vmess
EOF
}

menu() {
  cat <<'EOF'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 VPS TCP Optimize + Argo VMess+WS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. 执行全自动 TCP 优化（BBR v3 + 网络调优）
2. 安装/重装 Argo VMess + WS
3. 一键执行：TCP 优化 + Argo VMess + WS
4. 查看节点/订阅信息
5. 卸载 Argo VMess + WS
6. 安装 speed 快捷命令
7. 重启后继续安装
8. 环境检测
9. 结果摘要
10. 健康检查
0. 退出
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
  read -r -p "请输入选择: " choice
  case "$choice" in
    1) run_tcp_optimize ;;
    2) install_argo_vmess_ws ;;
    3) run_all ;;
    4) show_argo_vmess_ws_info ;;
    5) uninstall_argo_vmess_ws ;;
    6) install_shortcut ;;
    7) continue_after_reboot ;;
    8) check_environment ;;
    9) summarize_result ;;
    10) health_check ;;
    0) exit 0 ;;
    *) err "无效选择"; exit 1 ;;
  esac
}

case "${1:-}" in
  --optimize) run_tcp_optimize ;;
  --install-argo-vmess) install_argo_vmess_ws ;;
  --all) run_all ;;
  --continue) continue_after_reboot ;;
  --show-url) show_argo_vmess_ws_info ;;
  --uninstall-argo) uninstall_argo_vmess_ws ;;
  --write-config) write_argox_vmess_config ;;
  --install-shortcut) install_shortcut ;;
  --clear-state) clear_state ;;
  --check) check_environment ;;
  --summary) summarize_result ;;
  --health) health_check ;;
  -h|--help) usage ;;
  "") menu ;;
  *) err "未知参数：$1"; usage; exit 1 ;;
esac
